[log_halflife_minutes]
# Normal on the log-halflife
# but with priors on exp(mu)
# and exp(sigma) for readability
exp_loc = 10
exp_scale = 20

[t0_log10_titer_mode] # Normal on log10 TCID50/mL
loc = 5
scale = 2

[t0_log10_titer_sd] # TruncatedNormal, min 0
loc = 0
scale = 0.25
